[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.4"
constraintlayout = "2.2.1"
room = "2.8.4"
bcrypt = "0.4"
coreSplashscreen = "1.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime" ,version.ref = "room" }
bcrypt = { group = "org.mindrot", name = "jbcrypt", version.ref = "bcrypt" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

